[package]
name = "cairn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
cairn-core = { version = "0.1.0", path = "../core" }
cairn-server = { version = "0.1.0", path = "../server" }
clap = { version = "4.6.6", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true
